### ISSUE TITLE
A450JF 安装big sur

### ISSUE THREAD

**Issue by zwz-coding** [deku772/ASUS-A450J-X450JF-N550jv--EFI#1]
我下载了你最新的opencore 的efi尝试去安装big sur 到A450JF的机器，但是一直卡在苹果的界面，没有反应，我想请教下大神。以下是我的安装步骤：
1. 从黑果小兵那下载了big sur 11.0.1版本
2. 从你这里下载了opencore的efi
3. 通过clover configrator进行挂载做好的启动u盘，替换了efi
4. 安装机器，就卡着了。

**Comment by deku772** [comment]
the first.u should read my introduction.
我其实介绍当中有提到一句，请提前解锁你的主板CFG LOCK。
ITS EASY
这样会更加原生，如果没有解锁CFG，请使用相关配置软件，打开我的config.pllst
在有关cfg那里
kernel 前面两个app开头的勾选即可

不过我还是建议解锁cfg

**Comment by zwz-coding** [comment]
Thanks for your help, it is very helpful. 👍
