### ISSUE TITLE
BigSur bluetooth and HDMI not working

### ISSUE THREAD

**Issue by zwz-coding** [deku772/ASUS-A450J-X450JF-N550jv--EFI#2]
我更换了奋威的BCM94352HMB网卡，WIFI可以正常使用，但是蓝牙不能。HDMI也不能用。
我是直接使用您的OC EFI，请教下怎么解决，谢谢！

**Comment by deku772** [comment]
如果是最新的那个，那就是我最新的配置了

你可以重建缓存试试看

hdmi我没修复是因为我没有外接的显示器

**Comment by deku772** [comment]
已修复hdmi,请等待我提交
蓝牙因为我这里是正常的，所以没有办法测试。
你的隔空，接力这些是正常的吗？

**Comment by zwz-coding** [comment]
Hey deku772,
我已经通过直接修改/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist 文件，HDMI可以正常使用了。:-)
蓝牙功能在重启数次后，又恢复了，很奇怪。

Airdrop 因为蓝牙恢复工作，也相应开始工作了。

接力因为我没有完成三码注入，所以还是不能工作。

**Comment by zwz-coding** [comment]
我发现蓝牙功能会因为shutdown电脑后失效，在usb上也找不到bcm的网卡，你会这样吗？

**Comment by deku772** [comment]
> 我发现蓝牙功能会因为shutdown电脑后失效，在usb上也找不到bcm的网卡，你会这样吗？

一切正常，没有出现问题。
